Решение первой задачи
js-tasks-ru/jsbasic-20220113_realrocketrolla pull request #1
Opened 2022-01-08 20:26 UTC by realrocketrolla

2022-01-08 20:26 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2022-01-14 07:58 UTC, SinimaWath requested changes

2022-01-14 07:58 UTC, SinimaWath commented on 0-module/1-task/index.js
> +console.log( resultTwo );
Нужно из задач убирать тестовый код. Для того, чтобы проверить, работает код или нет: можно вызвать `npm test`

2022-01-14 07:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-14 19:18 UTC, SinimaWath approved these changes

2022-01-14 19:18 UTC, merged