решение задач 2-го модуля
js-tasks-ru/jsbasic-20220113_realrocketrolla pull request #3
Opened 2022-01-25 09:37 UTC by realrocketrolla

2022-01-25 09:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-25 11:32 UTC, SinimaWath requested changes

2022-01-25 11:32 UTC, SinimaWath commented on 2-module/3-task/index.js
> +window.calculator = calculator;
Убери лишний код из задач :) Из-за этого не проходят тесты

2022-01-25 12:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-01-26 11:00 UTC, SinimaWath approved these changes

2022-01-26 11:01 UTC, merged