Занятие 3: Функции и массивы
js-tasks-ru/jsbasic-20220113_realrocketrolla pull request #4
Opened 2022-01-29 18:44 UTC by realrocketrolla

2022-01-29 18:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-29 19:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-30 12:17 UTC, SinimaWath requested changes

2022-01-30 12:17 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Давай попробуем map

2022-01-30 12:17 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Давай попробуем filter + map, как в примере на лекции

2022-01-30 18:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-31 11:09 UTC, SinimaWath approved these changes
все ок :)

2022-01-31 11:10 UTC, merged