5 модуль
js-tasks-ru/jsbasic-20220113_realrocketrolla pull request #6
Opened 2022-02-14 16:40 UTC by realrocketrolla

2022-02-14 16:41 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-16 13:18 UTC, SinimaWath requested changes

2022-02-16 13:18 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  if (button.length < 1) {
Зачем тут проверка на length?

2022-02-16 13:18 UTC, SinimaWath commented on 5-module/2-task/index.js
> +	if (button.length < 1 || text.length < 1) {
Зачем тут проверка на length?

2022-02-16 13:18 UTC, SinimaWath commented on 5-module/2-task/index.js
> +		evt.preventDefault();
По клику на кнопку, нет действий по-умолчаний, поэтому этот код можно убрать

2022-02-16 13:18 UTC, SinimaWath commented on 5-module/1-task/index.js
> +    evt.preventDefault();
По клику на кнопку, нет действий по-умолчаний, поэтому этот код можно убрать

2022-02-16 13:18 UTC, SinimaWath commented on 5-module/3-task/index.js
> +		evt.preventDefault();
По клику на кнопку, нет действий по-умолчаний, поэтому этот код можно убрать

2022-02-16 13:18 UTC, SinimaWath commented on 5-module/3-task/index.js
> +		evt.preventDefault();
По клику на кнопку, нет действий по-умолчаний, поэтому этот код можно убрать

2022-02-16 18:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-18 09:55 UTC, SinimaWath approved these changes

2022-02-18 09:56 UTC, merged